name: dart_libp2p
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.3 <3.0.0'

dependencies:
  dart_multihash: ^0.0.1
  dart_cid: ^0.0.1
  multibase: ^1.0.0
  fixnum: ^1.1.0
  buffer: ^1.2.0
  bs58: ^1.0.2
  characters: ^1.3.0
  base_x: ^2.0.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
